### ISSUE TITLE
custom conda package for hub not installing it correctly

### ISSUE THREAD

**Issue by rsinha25** [jupyterhub/jupyterhub#1104]
Hi! I am trying to install jupyterhub on a server where I can't use pip. I have modified the login template file and I am trying to build the pip package into a conda installable using the following recipe: 

meta.yaml:
```
package:
  name: jupyterhub_custom
  version: "0.7.2"

source:
  path: ../../jupyterhub

build:
  noarch: python

requirements:
  build:
    - python

  run:
    - configurable-http-proxy
    - python
    - traitlets >=4.1
    - tornado >=4.1
    - jinja2
    - pamela
    - sqlalchemy
    - requests

test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all

```
build.sh:
```
$PYTHON setup.py single-version-externally-managed --record=record.txt    # Python command to install the script.

```

The package builds successfully but on starting jupyterhub, it gives errors as it cant find the templates (login.html, error.html etc). I checked the /path/to/anaconda/share/jupyter/ directory, and turns out it only has a folder with "kernels".

Can you tell me what's wrong with this recipe I have created? Or what I can do here to build it successfully?
