### ISSUE TITLE
Problem with getting API token when using Keycloak OAuth2 provider

### ISSUE THREAD

**Issue by Przybyszo** [jupyterhub/jupyterhub#2045]
Hi. Could I ask for some help with enabling third party oauth2 provider (keycloak) with jupyterhub? I have set up the following properties in the jupyter_config.yaml file
```
auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      client_id: "{{ hub.extraEnv.KEYCLOAK_CLIENT_ID }}"
      client_secret: "{{ hub.extraEnv.KEYCLOAK_CLIENT_SECRET }}"
      token_url: https://{{ hub.extraEnv.KEYCLOAK_HOST }}/auth/realms/{{ hub.extraEnv.KEYCLOAK_REALM }}/protocol/openid-connect/token
      userdata_url: https://{{ hub.extraEnv.KEYCLOAK_HOST }}/auth/realms/{{ hub.extraEnv.KEYCLOAK_REALM }}/protocol/openid-connect/userinfo
      userdata_method: GET
      userdata_params: {'state': 'state'}
      username_key: preferred_username
```
And also added necessary environment variables to hub:
```
                'OAUTH2_AUTHORIZE_URL': 'https://auth.%s/auth/realms/ldap/protocol/openid-connect/auth' % config['general']['domain'],
                'OAUTH2_TOKEN_URL': 'https://auth.%s/auth/realms/ldap/protocol/openid-connect/token' % config['general']['domain'],
```

Logging into jupyterhub redirects me to keycloak, and after logging in I get authenticated and get back to my singleuser instance. Great. The problem is, that I also want to retrieve the jupyterhub API token from jupyterhub. I saw there are two endpoints ( `/oauth2/authorize` and `/oauth2/token`). The problem is, I don't know that parameters to put into those calls to get the API key. I can see in the sqlite database, that there are tables such as `oauth_clients`, and their identifiers are e.g. user-test, user-test2. Why do I have new client_ids, that are different from what I have set up in the configuration file (the keycloak's client id and secret)? Thanks for your help in advance
