### ISSUE TITLE
[HELP] Installation of Jupyterhub in Kubernetes behind nginx-ingress

### ISSUE THREAD

**Issue by DewinGoh** [jupyterhub/jupyterhub#2372]
Hi, I'm facing problems with installation of Jupyterhub on a Kubernetes cluster.

The Kubernetes setup is such that all applications use a single ingress point (single nginx-ingress application) with ssl terminated behind it (only http within the cluster). As such, for the proxy, I opted for a ClusterIP instead. The exact config, in the values that override values.yaml, goes like this:

proxy:
  secretToken: "blah"
  service:
    type: ClusterIP
  https:
    enabled: false

ingress:
  enabled: true
  hosts:
    - "myhost.com"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

The hub can start up, create notebooks, but it always is unable to connect to the notebook kernels. The error message thrown always involves the following responses:

[W 2019-01-04 04:32:00.788 SingleUserNotebookApp log:158] 404 GET /user/ME/nbextensions/widgets/notebook/js/extension.js?v=20190104034733 (myip@blah) 2.01ms

[W 2019-01-04 04:32:01.395 SingleUserNotebookApp log:158] 400 GET /user/ME/api/kernels/0ef17bce-dfc6-49a9-9680-fa2c1ac71cd4/channels?session_id=15a4d5ba69174c488a7d32f31a3c2d4d (myip@blah) 47.32ms

I believe it is an issue involving the proxy, but am unable to pinpoint the exact problem. It would help greatly if someone here knows how to resolve this issue/ explain what the problem is.

Thank you.

**Comment by yceoshda** [comment]
Hi,

We are trying to do something similar and are getting even worse results ("Empty Reply from Server").
Have you found anything yet ?

Here is the proxy part of our config

```yaml
proxy:
  secretToken: supersecrettoken
  service:
    type: NodePort
  https:
    enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" # ssl termination is done before reaching this
  hosts:
    - myjupyter.url
```
