### ISSUE TITLE
Configure options_form (or profile_list) for individual users

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2390]
# What I want
I want to configure the users individual `spawner.options_form` (through KubeSpawner's `profile_list`) based on information provided by my identity provider for each authenticated user individually.

# Why I want this
When a user login, my JupyterHub currently receives information in a custom _claim_ called `gpu_access`. This is something that I've setup in [Okta](https://www.okta.com/) to be provided as a boolean based on if the user belongs to a specific group called GPU Access that I can manage nicely from an UI.

I want to utilize this information to decide what options the user could choose from when spawning. Should the user for example be allowed to utilize a dedicated GPU node?

# Code investigation
These are conclusions drawn from investigating JupyterHub's source code:
- The `pre_spawn_start` and `pre_spawn_hook` are called from within `spawn`.
- `spawn` is called from within `spawn_single_user`.
- `options_form` is evaluated before `spawn_single_user` is invoked in order to provide it with chosen options.

### auth.py / class Authenticator / pre_spawn_start()
https://github.com/jupyterhub/jupyterhub/blob/0e6cf6a485b244c8b02e0da0269648c0de6370f7/jupyterhub/auth.py#L358-L362

### auth.py / class Spawner / pre_spawn_hook()
https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/spawner.py#L541-L561

### user.py / class User / spawn()
This is where `pre_spawn_start` and `pre_spawn_hook` are invoked.
https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/user.py#L437-L451

### base.py / class BaseHandler / spawn_single_user()
This is where `spawn()` is invoked.
https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/handlers/base.py#L714

### base.py / class UserSpawnHandler / get()
https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/handlers/base.py#L1188-L1199

# Request for input
Before deciding to either support or not support configuring `options_form` on a per user basis, it seems reasonable to evaluate how it could be done first. So my request for input is regarding this how we could go about this.

Would we add another hook?
Where would we need to run it?
What arguments would we pass it?

## Ideas
Perhaps we could add a `user_refreshed_hook` on refreshed user state, that we would invoke from this method called `auth_to_user`? I think **this is my recommended solution**. But, I'm a bit uncertain, does this mean we need to allow the BaseHandler to be configurable with a traitlet? What is the @property fields doing? Hmmm...

https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/handlers/base.py#L560-L595

Perhaps we could add a `user_auth_state_updated_hook` whenever `auth_state` is updated/saved? The benefit of this is that we would do things whenever auth_state was updated, no matter if it was through a login etc or something else saved something to the users auth_state. The downside, is that perhaps we want to use a hook like this even though we don't save the auth_state.

https://github.com/jupyterhub/jupyterhub/blob/392e432071c21070ab3d54ab2cb72c8bda09e6f4/jupyterhub/user.py#L161-L167

**Comment by consideRatio** [comment]
@minrk what do you think? If you think it make sense and provide a direction I'll write a PR for this.

**Comment by minrk** [comment]
options_form is already configurable per-user, since it can be a callable, which can do arbitrary things based on `self.user`, including based on `await self.user.get_auth_state()`.

`pre_spawn_start` doesn't seem like the right hook for something that doesn't happen prior to spawn, but instead happens prior to requesting the options form as *input* to the spawn. If we need a new hook for that, it should be added, but I suspect that the existing async `.options_form` hook is enough. For your case, it sounds like I would write this hook:

```python
async def get_options_form(spawner):
    auth_state = await spawner.user.get_auth_state()
    has_gpu = auth_state.get('gpu-access')
    if has_gpu:
        return '<gpu form...>'
    else:
        return '<non-gpu form...>'

c.MySpawner.options_form = get_options_form
```

Does that work for you? It doesn't sound like anything would be accomplished by the additional hooks, to me, and I'd like to keep them to a minimum if we can.

**Comment by consideRatio** [comment]
@minrk thanks for taking the time to process my blob of text! This seems like an excellent example I did not consider! I'll investigate and follow up!

**Comment by consideRatio** [comment]
Thanks for the help @minrk !

I wanted to utilize `profile_list` by `KubeSpawner` and found the following to be a working solution to do that.

```yaml
hub:
  extraConfig:
    spawner: |
      from kubespawner import KubeSpawner

      class CustomKubeSpawner(KubeSpawner):
          # Override the options_form presented for users if they have gpu_access.
          # See: https://github.com/jupyterhub/jupyterhub/issues/2390 for related details
          async def options_form(self, spawner):
              auth_state = await self.user.get_auth_state()
              user_details = auth_state['oauth_user']

              username = user_details['preferred_username']
              gpu_access = user_details['gpu_access'] # type: bool

              # Dynamically provide a profile_list for those with GPU Access
              # ------------------------------------------------------------------
              # NOTE: This is setup using a custom scope and claim called gpu_access
              # NOTE: Claims are info provided after requesting certain Scopes.
              #       These are configurable in our Okta instance.
              if gpu_access:
                  self.log.info(f'GPU access options will be presented for {username}.')
                  self.profile_list = [
                      {
                          'default': True,
                          'display_name': 'Shared, 8 CPU cores',
                          'description': 'Your code will run on a shared machine. This will already be running and you should be up and running in 30 seconds or less.',
                      },            
                      {
                          'display_name': 'Personal, 4 CPU cores & 26GB RAM, 1 NVIDIA Tesla K80 GPU',
                          'description': 'Your code will run on a computer dedicated to you. No such computer is available ahead of time, so you need to wait 5-15 minutes before it is ready.',
                          'kubespawner_override': {
                              'image': 'eu.gcr.io/ds-platform/dsp-user-environment-gpu:c3959b5',
                              'extra_resource_limits': {
                                  'nvidia.com/gpu': '1',
                              },
                              'node_selector': {
                                  'gpu': 'k80',
                              },
                          },
                      },
                      {
                          'display_name': "Personal, 4 CPU cores & 26GB RAM, 1 NVIDIA Tesla P100 GPU",
                          'description': 'Your code will run on a computer dedicated to you. No such computer is available ahead of time, so you need to wait 5-15 minutes before it is ready.',
                          'kubespawner_override': {
                              'image': 'eu.gcr.io/ds-platform/dsp-user-environment-gpu:c3959b5',
                              'extra_resource_limits': {
                                  'nvidia.com/gpu': '1',
                              },
                              'node_selector': {
                                  'gpu': 'p100',
                              },
                          },
                      },
                  ]
              
              return super().options_form
              
      c.JupyterHub.spawner_class = CustomKubeSpawner
```
