### ISSUE TITLE
Configuring SSL with load balancer in helm chart config does not work

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/jupyterhub#2450]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**
Configuring SSL in jupyterhub helm chart does not work, per [Off-loading SSL to a Load Balancer](https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#off-loading-ssl-to-a-load-balancer)
When I install the chart on my cluster, the ELB has only one listener: HTTP (port 80) .

My helm chart config looks like so:
```
proxy:
  secretToken: "<redacted>"
  https:
    enabled: true
    type: offload
  service:
    annotations:
      # Certificate ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<redacted>"
      # The protocol to use on the backend, we use TCP since we're using websockets
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Which ports should use SSL
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '1800'
```

**To Reproduce**

**Expected behavior**
I expect a SSL listener to be configured
