### ISSUE TITLE
Possible to use custom unix user ?

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/jupyterhub#2466]
It seems that by default, jupyterhub notebook servers get a default unix user `jovyan`. Is there any way to have the unix user be the same name as the jupyterhub user? (Github in my case)

Just a shot in the dark guess, but is there some `multiUser` helm chart config section that can be used? Instead of `singleUser`? 

My config is fairly simple, it looks like this. 

```
proxy:
  secretToken: ""
  # ...

auth:
  admin:
    access: true
    users:
      - ...
  type: github
  github:
    clientId: " ... "
    clientSecret: " ... "
    callbackUrl: " ... "
    org_whitelist:
      - "<org>"
    scopes:
      - "read:user"

singleuser:
  image:
    name: <account>.dkr.ecr.eu-west-1.amazonaws.com/<repo>
    tag: v5
```
