### ISSUE TITLE
Not sure how to set path c.JupyterHub.template_paths

### ISSUE THREAD

**Issue by mlpjesse** [jupyterhub/jupyterhub#2472]
Hi I am trying to customize templates on jupyterhub. I have a server set up on kubernetes and google cloud that is currently fine but I'm having trouble figuring out how to specify the path for the template paths. I have a simple 'templates' folder with a 404.html file that just changes the message the 404 displays. My .yaml file looks like this:
```
hub:
  extraConfig:
    template_landing: |
      c.JupyterHub.template_paths = ['./templates/']
```

I couldn't find anywhere how to properly specify the templates folder or if I have to move this folder somewhere (I am new to kubernetes so its just in my local directory where i run the helm upgrade command). Any help would be appreciated. Thanks!
