### ISSUE TITLE
[Question] Jupyter lab kernels

### ISSUE THREAD

**Issue by emirot** [jupyterhub/jupyterhub#2473]
Hi there,

I see the kernels in Jupyter Hub but not in jupyter lab. 

```
proxy:
  secretToken: "mysecret"
  service:
    type: NodePort

singleuser:
  # Defines the default image
  defaultUrl: "/lab"
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
```

Any idea why ? 

Thanks
