### ISSUE TITLE
Unable to start jupyterhub "Failed to connect to Hub API"

### ISSUE THREAD

**Issue by 1krutarth** [jupyterhub/jupyterhub#2537]
Hello folks,

Let me give a background on the setup before I dive deep in configurations.

**Setup**:
A hub is run inside a docker, call it `customhub` using `DockerSpawner` and `GithubOAuthenticator`. Docker engine runs on MacOS Sierra. Motivated from https://github.com/jupyterhub/jupyterhub-deploy-docker with some changes around authenticator, spawner and not using postgres (relying on sqlite atm).

**Issue**
```Failed to connect to Hub API at 'http://0.0.0.0:8081/hub/api'.  Is the Hub accessible at this URL (from host: 2cb04c784ff9)?```
But when I go `http://0.0.0.0:8081/hub/api` this from chrome browser it returns `{"version": "0.9.6"}`
Tried to follow https://github.com/jupyterhub/dockerspawner/issues/198 except being unable to allow 8081 like mentioned here: https://github.com/jupyterhub/dockerspawner/issues/198#issuecomment-404412344
(I don't have `ufw` in mac and don't know the alternative).

**Notebook Configuration**
`Dockerfile` to create notebook image `customuser`
```dockerfile
ARG BASE_IMAGE=jupyter/base-notebook
FROM $BASE_IMAGE

ADD nbooks/* $HOME/notebooks
RUN python3 -m pip install --no-cache jupyterhub==0.9.6 && python3 -m pip install notebook
```
Build image: `docker build -t customuser .`
Builds: `customuser:latest`

**Hub Configuration**
`docker-compose.yml` looks like:

```yaml
version: "2"

services:
  hub:
    build:
      context: "."
      dockerfile: Dockerfile
    image: customhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8081:8081"
    env_file:
      - .env
      - secrets/oauth.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
```

`Dockerfile` looks like:
```dockerfile
FROM jupyterhub/jupyterhub-onbuild:0.9.6

RUN /opt/conda/bin/pip install --no-cache-dir \
    oauthenticator==0.8.* \
    dockerspawner==0.9.*
```

`jupyterhub_config.py`:
```python
import os

c = get_config()

# DockerSpawner configuration
network_name = os.environ['DOCKER_NETWORK_NAME']
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/user/notebooks'

c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = os.environ['DOCKER_NOTEBOOK_IMAGE']
c.DockerSpawner.network_name = network_name
c.DockerSpawner.extra_host_config = { 'network_mode': network_name }
c.DockerSpawner.remove_containers = True
c.DockerSpawner.debug = True
c.DockerSpawner.hub_ip_connect='0.0.0.0'

# OAuth with GitHub
from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.GitHubOAuthenticator.oauth_callback_url = os.environ['OAUTH_CALLBACK_URL']
c.GitHubOAuthenticator.client_id = os.environ['OAUTH_CLIENT_ID']
c.GitHubOAuthenticator.client_secret = os.environ['OAUTH_CLIENT_SECRET']

# JupyterHub configuration
c.JupyterHub.hub_ip = '0.0.0.0'
c.NotebookApp.ip = '0.0.0.0'
```
