### ISSUE TITLE
Unable to access API with generated API key

### ISSUE THREAD

**Issue by caseyzak24** [jupyterhub/jupyterhub#2607]
### Basic Problem ###
I've followed the available Jupyterhub tutorials to set up a jupyterhub in a docker-compose network. When I try to GET any endpoint of the hub API using a valid API key (e.g. http://localhost:8000/hub/api/users) I get a 403. I am authenticating with a `{"token": key}` field in the header of the request.

However, if I just GET the index of the API (http://localhost:8000/hub/api/) then I get a 200 and the expected message giving the version number (this seems to work even if I don't include a header). That indicates that the hub is reachable locally, outside of the docker network.

The log output on the hub is simply
```
jupyterhub | [I 2019-06-10 22:00:54.925 JupyterHub log:174] 200 GET /hub/api/ (@192.168.32.3) 2.77ms
jupyterhub | [W 2019-06-10 22:01:02.806 JupyterHub log:174] 403 GET /hub/api/users (@192.168.32.3) 6.73ms
```

So I don't have additional information to determine why the 403 is being raised.

### Troubleshooting Undertaken So Far ###
- I am able to access the hub on my local network via the browser and login as the user I set up on the hub machine (just using the standard PAM right now).
- I have tried using the API token that I specified with `c.JupyterHub.services` in `jupyter_config.py`. I have also logged in via the browser and generated a new API key and tried that
- I have confirmed that in both API-generating-cases the API key is being added to the table in the hub's .sql database

If this is a simple mistake on my part I apologize, but I think what I am encountering is at least a lack of documentation/logging on the hub that would allow me to troubleshoot this issue more effectively.

### Code ###

docker-compose.yml
```
version: "2"

services:
  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      PGDATA: "/pgdata"
      POSTGRES_PASSWORD: postgres
    volumes:
      - "db:/pgdata"
  hub:
    build:
      context: ..
      dockerfile: Dockerfile.jupyterhub-e2e
      args:
        TEST_USER: test.user
        TEST_USER_PASS: chupacabra
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "8000:80"
      - "8081:8081"
    environment:
      - JUPYTERHUB_IP_CONNECT=jupyterhub
      - JUPYTERHUB_PORT=80
      - DOCKER_NETWORK_NAME=jupyterhub_network
      - TEST_USER=test.user
      - TEST_API_KEY=bda1f94975ba41bd87ba3616dc36e6cc
    links:
      - hub-db
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --debug
volumes:
  test-output-vol:
  db:
networks:
  default:
    external:
      name: jupyterhub_network
```

Dockerfile.jupyterhub-e2e
```
FROM jupyterhub/jupyterhub:latest
RUN pip install --no-cache-dir dockerspawner python-dotenv
ARG TEST_USER
ARG TEST_USER_PASS
RUN mkdir /opt/shared-notebooks
RUN mkdir /etc/jupyterhub
RUN touch /opt/.env
COPY jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py
RUN useradd --create-home ${TEST_USER}
RUN /bin/bash -c "echo -e '${TEST_USER_PASS}\n${TEST_USER_PASS}' | passwd ${TEST_USER}"
```

jupyterhub_config.py
```
import os
c.JupyterHub.port = int(os.getenv('JUPYTERHUB_PORT')) or 80
c.JupyterHub.hub_ip = '0.0.0.0'  # listen on all interfaces
c.JupyterHub.hub_connect_ip = os.environ.get('JUPYTERHUB_IP_CONNECT', '172.17.0.1')
test_api_key = os.getenv('TEST_API_KEY')
if test_api_key is not None:
    c.JupyterHub.services = [{'name': 'start-single-user-server', 'api_token': test_api_key}, ]
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
network_name = os.getenv('DOCKER_NETWORK_NAME')
if network_name is not None:
    c.DockerSpawner.network_name = network_name
    c.DockerSpawner.extra_host_config = {'network_mode': network_name}
c.DockerSpawner.notebook_dir = "/root/"
c.DockerSpawner.volumes = {"/home/{username}": "/root/", '/opt/shared-notebooks': '/root/shared/'}
from dotenv import dotenv_values
c.DockerSpawner.environment = dotenv_values(dotenv_path="/opt/.env")
c.Spawner.cmd = ["jupyterhub-singleuser", "--allow-root"]
c.DockerSpawner.image = 'myimage:latest'
c.DockerSpawner.remove = True
c.DockerSpawner.debug = True
c.Authenticator.admin_users = {'user.one', 'user.two'}
```
