### ISSUE TITLE
PAMAuthenticator can't use post auth hook

### ISSUE THREAD

**Issue by Wildcarde** [jupyterhub/jupyterhub#2703]
**Describe the bug**
I'm attempting to retrieve the gids/group list for a user on the way in so that I can handle admin access via groups as well as configure whether the user should have access to the credentials for nbgrader (containers are being launched in swarm). And while I can do PAM auth in the container I can't populate 'auth_state''spawn_data' with the example code instead it produces the following: [W 2019-08-23 18:51:00.498 JupyterHub configurable:168] Config option `post_auth_hook` not recognized by `PAMAuthenticator`.

**To Reproduce**
1. Prop up a standard jupyterhub authenticating through the `login` service on pam
2. follow the instructions in https://jupyterhub.readthedocs.io/en/stable/api/auth.html#pamauthenticator

**Expected behavior**
I would like to retrieve the groups / group ids so that I can make spawner decisions in order to isolate students and teachers/tas.

**Additional context**
I've been working on this for a while now and have to following overall structure:
Note: this is all currently standardized on jupyterhub 0.9.4 at this time.
docker in swarm mode (modern not deprecated)
I'm mounting docker.sock into a compose file along with pam/sssd and the swarm's network. This is launched on the manager node directly.  Auth works, access to the swarm network works, swarmlauncher starts containers. 
A pre spawner hook creates home directories for people if they don't already exist.
All of the above works as expected.
I'm now attempting to resolve capturing user groups so that I can make the nbgrader side of this problem work which is where I'm running into this problem.

In case it helps, docker-compose.yml:
```
version: "3"
services:
  proxy:
    env_file: .env
    image: jupyterhub/configurable-http-proxy:3.1.1
    # expose the proxy to the world
    ports:
      - "8000:8000"
    command:
      - configurable-http-proxy
      - '--error-target'
      - 'http://hub/hub/error'

  hub:
    # build an image with SwarmSpawner and our jupyterhub_config.py
    env_file: .env
    build:
      context: "."
      dockerfile: "jhub.Dockerfile"
    # mount the docker socket
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/pam.d/:/etc/pam.d/:ro"
      - "/etc/nsswitch.conf:/etc/nsswitch.conf:ro"
      - "/var/lib/sss/pipes/:/var/lib/sss/pipes/:rw"
      - "/nfs/home/:/nfs/home/:rw"
    environment:
      DOCKER_NETWORK_NAME: 'jhub-swarmnet'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  default:
    external:
      name: jhub-swarmnet
```
