### ISSUE TITLE
jupyterhub exited with code 1: Found database schema version 4dc2d5a8c53c != 896818069c98

### ISSUE THREAD

**Issue by relyativist** [jupyterhub/jupyterhub#2711]
Hi! Thanks for using JupyterHub.

If you are reporting an issue with JupyterHub, please use the [GitHub issue](https://github.com/jupyterhub/jupyterhub/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

**Describe the bug**

**To Reproduce**
1. add to docker-compose.yml:
```
jupyterhub:
    #Config for Hub+proxy
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
    restart: on-failure
```
2. Jupyterhub-config.py
```
import os

## Generic
c.JupyterHub.admin_access = True
c.Spawner.default_url = '/lab'

## Authenticator
from jhub_cas_authenticator.cas_auth import CASAuthenticator
c.JupyterHub.authenticator_class = CASAuthenticator

# The CAS URLs to redirect (un)authenticated users to.
c.CASAuthenticator.cas_login_url = 'https://ironman/login'
c.CASLocalAuthenticator.cas_logout_url = 'https://ironman/logout'

# The CAS endpoint for validating service tickets.
c.CASAuthenticator.cas_service_validate_url = 'https://ironman/serviceValidate'

# The service URL the CAS server will redirect the browser back to on successful authentication.
c.CASAuthenticator.cas_service_url = 'https://%s/hub/login' % os.environ['HOST']

c.Authenticator.admin_users = { 'lucadefe' }

## Docker spawner
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.image = os.environ['DOCKER_JUPYTER_CONTAINER']
c.DockerSpawner.network_name = os.environ['DOCKER_NETWORK_NAME']
# See https://github.com/jupyterhub/dockerspawner/blob/master/examples/oauth/jupyterhub_config.py
#c.JupyterHub.hub_ip = os.environ['HUB_IP']
c.JupyterHub.hub_ip = os.environ['HUB_IP']

# user data persistence
# see https://github.com/jupyterhub/dockerspawner#data-persistence-and-dockerspawner
notebook_dir = os.environ.get('DOCKER_NOTEBOOK_DIR') or '/home/jovyan'
c.DockerSpawner.notebook_dir = notebook_dir
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir }

# Other stuff
c.Spawner.cpu_limit = 1
c.Spawner.mem_limit = '10G'


# Services
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': [sys.executable, 'cull_idle_servers.py', '--timeout=3600'],
    }
]
```

**Expected behavior**
```
jupyterhub       | [I 2019-08-30 08:33:35.857 JupyterHub app:1667] Using Authenticator: jhub_cas_authenticator.cas_auth.CASAuthenticator
jupyterhub       | [I 2019-08-30 08:33:35.857 JupyterHub app:1667] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-0.10.0
jupyterhub       | [I 2019-08-30 08:33:35.860 JupyterHub app:1014] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
jupyterhub       | Found database schema version 4dc2d5a8c53c != 896818069c98. Backup your database and run `jupyterhub upgrade-db` to upgrade to the latest schema.
jupyterhub exited with code 1
```

**Desktop (please complete the following information):**
 - OS: linux mint
