### ISSUE TITLE
OAuth Redirect from non www

### ISSUE THREAD

**Issue by akaszynski** [jupyterhub/jupyterhub#2777]
I'd first like to say thank you to all the developers who put in their time working on Jupyterhub.  This is excellent software!

I'm having an issue where the user can't log in when trying to login from domain.com instead of www.domain.com.  I think the issue comes down to the fact that the redirect URL is for the www.domain.com/hub/

```
auth:
  type: custom
  custom:
    className: "oauthenticator.azuread.AzureAdOAuthenticator"
    config:
      client_id: "redacted"
      client_secret: "redacted"
      oauth_callback_url: "https://www.domain.com/hub/oauth_callback"
      tenant_id: "XXXXXXXXXXXXXXXXXXXXXXXXX"
```

Is there any way to change the url depending on the site used by the user?  Or is there a way to redirect all traffic from https://domain.com to https://www.domain.com?

Thanks again for your help!
