### ISSUE TITLE
Missing HTTP security headers

### ISSUE THREAD

**Issue by DarkmatterVale** [jupyterhub/jupyterhub#3113]
### Bug description
When I visit the main webpage of JupyterHub, a number of security headers are missing:

- "Strict-Transport-Security"
- "X-Frame-Options"
- "X-Content-Type-Options"
- "X-XSS-Protection"
-  [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src) default-src and script-src

#### Expected behaviour
I expect the aforementioned headers be set.

#### Actual behaviour
These headers are not set.

### How to reproduce
1. Setup and run JupyterHub 1.1.0
2. Proceed to the hub's root ("localhost:<PORT>/") webpage
3. Look at the response headers

### Your personal set up
 - EKS
 - Version: [z2j-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) chart v0.9.0 (JupyterHub version 1.1.0)
 - Configuration:
```
proxy:
  https:
    enabled: true
    type: offload
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "---------------"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
```
