### ISSUE TITLE
Missing documentation for endpoint  ​/users​/{name}​/servers​/{server_name}.

### ISSUE THREAD

**Issue by synchronizing** [jupyterhub/jupyterhub#3158]
### Bug description
JupyterHub will not spawn a named-server if a certain number of characters is used for `{server_name}`. 

#### Expected behaviour
Either proper documentation on the REST API, or a fix to allow any sized name for `{server_name}`. [Documentation reference](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/docs/rest-api.yml#/default/post_users__name__servers__server_name_).

#### Actual behaviour

![Screen Shot 2020-08-26 at 6 34 35 PM](https://user-images.githubusercontent.com/2829082/91363534-d3244100-e7ca-11ea-9584-8a169f9f6850.png)

### How to reproduce

The following code will not work:

```python
import random
import hashlib
import requests

def random_md5_hash():
    random_number = str(random.getrandbits(128)).encode()
    return hashlib.md5(random_number).hexdigest()

url = ""
uri = f"http://{url}/hub/api"
headers = {"Authorization": "token <token>"}
name = random_md5_hash() # Variation of e607762dcff6494821cadcd6cce08eb3 (md5 hash). 
project = random_md5_hash() 

# Queries user. If it does not exist, creates it.
user = requests.get(f"{uri}/users/{name}", headers=headers).json()
if "status" in user and user["status"] == 404:
    user = requests.post(f"{uri}/users/{name}", headers=headers).json()

# Creates notebook for the user to use.
server = requests.post(f"{uri}/users/{name}/servers/{project}", headers=headers).text

# Prints the notebook URL.
print(f"http://{url}/user/{name}/{project}/lab")
```

However, the moment this line:

```python
project = random_md5_hash() 
```

is changed to:

```python
project = "1"
```

Works, and I am able to access the new user's named-server at the printed out URL (after logging in with bogus login).

### Your personal set up

JupyterHub + Kubernetes running on gCloud. Latest version according to Zero-to-JupyterHub tutorial (`0.9.0`). `config.yaml` looks like so:

```yaml

# JupyterHub specific configuration.
hub:

  # Key to sign cookies.
  cookieSecret: 9ce41e753c9fd45aebeb5331c5264efb71143a3e5e9e04045a1bc4bdc48a6004

  # Services that have access to JupyterHub API.
  # Admin in the context of utilizing the JupyterHub RESTFul API.
  services:
    <service_name>:
      admin: true
      apiToken: <api_token>

  # Extra configuration for JupyterHub.
  extraConfig:
    binder: |

      # Disable webpage based login. Users are created via API only.
      # c.JupyterHub.authenticator_class = 'nullauthenticator.NullAuthenticator'

      # Allows users to have multiple notebooks.
      c.JupyterHub.allow_named_servers = True

# Authentication configuration for JupyterHub specifically.
# Admin in the context of logging into the frontend portal.
auth:
  admin:
    users:
      - admin

# Spawned Jupyter Notebook configuration.
singleuser:
  defaultUrl: "/lab"

# Kubernetes-JupyterHub integration configuration.
proxy:
  secretToken: <proxy_secret>
```
