### ISSUE TITLE
Access Hub on EKS through ambassador

### ISSUE THREAD

**Issue by ntorba** [jupyterhub/jupyterhub#3216]
### Proposed change

I would like to access JupyterHub on EKS through ambassador, instead of creating a new load balancer specific to the Hub service. 

### Alternative options

Not using ambassador 

### Who would use this feature?

Users of ambassador on kubernetes 

### (Optional): Suggest a solution

I am currently trying to run jupyterhub on an EKS cluster that I have already setup ambassador for.
Because I have ambassador setup, I thought it made sense that I could create a new mapping to handle connections instead of having jupyterhub use it’s own loadbalancer.
Here is my config for the mapping I created:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jhub-mapping
  namespace: jhub
spec:
  prefix: /ampjhub/
  service: proxy-api
```
When I visited https://my_url/ampjhub/ I receive `upstream request timeout`.

I also tried mapping directly to hub service, but got the same result.

I was not sure if this was a bug, a bad setup, or if there is some reason this is not supported. 

Thanks!
