### ISSUE TITLE
404 on accessing user container with Dockerspawner

### ISSUE THREAD

**Issue by ramdesh** [jupyterhub/jupyterhub#3408]
### Bug description

I am using Jupyterhub 1.3.0 and Jupyterlab 3.0.1 and spawning a custom image based on `minimal-notebook` using Dockerspawner. The user server spawns fine, but when I try to access it using Jupyterhub, it gives a 404 error. Upon inspecting logs in the user container, I noticed that it was generating this error: https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/services/auth.py#L505

#### Expected behaviour

User would be able to access their lab instance spawned using Dockerspawner using Jupyterhub.

#### Actual behaviour

The user is not able to access their lab instance, and receives a 404 error instead.

### How to reproduce

1. Spawn a new lab server using Jupyterhub
2. Try to access the server
3. Receive '404 Page Not Found' error

### Your personal set up

 - OS:
 
 - Version(s): macOS 10.15, Jupyterhub 1.3.0, Jupyterlab 3.0.1
 

- <details><summary>Full environment</summary>

`Dockerfile.jupyterhub`

```
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyterhub/jupyterhub:1.3.0

RUN pip install --no-cache-dir \
               jupyter \
               jupyterhub==$JUPYTERHUB_VERSION \
               jupyterlab==3.0.1 \
               jupyterhub-ldapauthenticator \
               jupyterhub-dummyauthenticator \
               dockerspawner \
               psycopg2-binary



SHELL ["/bin/bash", "-c"]


COPY "jupyterhub_config.py" "/srv/jupyterhub/jupyterhub_config.py"
```

`Dockerfile.notebook`

```
FROM jupyter/minimal-notebook:latest

RUN pip install --no-cache-dir \
               jupyter \
               jupyterhub==1.3.0 \
               jupyterlab==3.0.1 \
               jupyterhub-ldapauthenticator \
               jupyterhub-dummyauthenticator \
               dockerspawner \
               py4j \
               requests \
               psycopg2-binary \
               sqlalchemy \
               pandas \
               dockerspawner \
               jupyterlab_code_formatter \
               autopep8 \


SHELL ["/bin/bash", "-c"]
```

`docker-compose.yml`

```
version: "3.5"

hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    networks:
      jupyterhub-network:
        ipv4_address: 172.16.238.16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"


hub:
    depends_on:
      - hub-db
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile.jupyterhub
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      jupyterhub-network:
        ipv4_address: 172.16.238.12
    ports:
      - "8000:8000"
    links:
      - hub-db
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: jupyterhub-db
      POSTGRES_PASSWORD: ${JPY_PSQL_PASSWORD}
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --debug

singleuser:
    image: jupyter_singleuser
    build:
      context: ./notebook
      dockerfile: Dockerfile.notebook
    volumes:
      - "/srv/jupyter:/etc/jupyter"
    command: >
      ls -la /etc/jupyter

networks:
  jupyterhub-network:
    name: jupyterhub-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```

</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py

c = get_config()
import os
import subprocess
## File to write PID Useful for daemonizing jupyterhub.
c.JupyterHub.pid_file = '/var/run/jupyter.pid'

## The public facing network settings of the whole application (the proxy)
c.JupyterHub.ip = ''
c.JupyterHub.port = 8000
c.JupyterHub.ssl_key = ''
c.JupyterHub.ssl_cert = ''

# set network settings for the jupyterhub process
c.JupyterHub.hub_ip = 'jupyterhub'
c.JupyterHub.hub_port = 8081

c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/jupyterhub_cookie_secret'

c.JupyterHub.internal_ssl = False
# use PAM Authenticator for local users
c.JupyterHub.authenticator_class = 'dummyauthenticator.DummyAuthenticator'

# specify users and admin
c.Authenticator.whitelist = set(['test'])
c.Authenticator.admin_users = set(['test'])
c.DummyAuthenticator.password = "admin1234"

c.Spawner.cmd = ['start-singleuser.sh']
c.Spawner.notebook_dir = '/home/jovyan/work'
c.Spawner.default_url = '/lab'
c.Spawner.debug = True

#Spawner Config
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
network_name = 'jupyterhub-network'
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.network_name = network_name
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': '/home/jovyan/work' }
c.DockerSpawner.remove_containers = True
c.DockerSpawner.host_ip = '0.0.0.0'
c.DockerSpawner.image = 'jupyter_singleuser'
data_dir = '/data'

c.JupyterHub.cookie_secret_file = os.path.join(data_dir, 'jupyterhub_cookie_secret')
c.Spawner.mem_limit = '1.5G'
c.Spawner.mem_guarantee = '512M'
c.Spawner.cpu_limit = 2
c.Spawner.cpu_guarantee = 0.5


```
</details>

- <details><summary>Logs</summary>

The error log message I see inside the user container is `No user identified` as seen in this code: https://github.com/jupyterhub/jupyterhub/blob/c5bfd2800542f977528720c0cc8c56684f0da380/jupyterhub/services/auth.py#L505
</details>
