### ISSUE TITLE
LocalAuthenticator does not detect user password change or new users

### ISSUE THREAD

**Issue by halecakir** [jupyterhub/jupyterhub#3766]
Hi,
I am using LocalAuthenticator and whenever I change the user password or create a new user in the host, I need to restart Jupyterhub container.
Is there any way to sync user info with Jupyterhub container which enables us to login hub without restarting the hub container?

Here is my compose file:

```
version: '2.3'

services:
  jupyterhub:
    build: ./jupyterhub
    ports:
      - "8080:8000"
    container_name: jupyterhub-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
```
