### ISSUE TITLE
Google Authenticator breaks on upgrade to latest helmchart `3.0.0-beta.3.git.6268.h16086582`

### ISSUE THREAD

**Issue by taylorgibson** [jupyterhub/jupyterhub#4526]
### Bug description

I recently upgraded from helm-chart `3.0.0-alpha.1.git.6194.h835c3fa8` --> `3.0.0-beta.3.git.6268.h16086582`. After successfully upgrading without errors or warnings, when attempting to authenticate using the Google Authenticator I would receive a 403 Forbidden error message.  My `config.yaml` lists a single `hosted_domain`:

```
hub:
  config:
    Authenticator:
      admin_users:
        - <my_user_account>
    GoogleOAuthenticator:
      client_id: <my_client_id>
      client_secret: <my_client_secret>
      oauth_callback_url: <my_callback_url>
      hosted_domain:
        - <my_domain>
      login_service: <my_school_name>
    JupyterHub:
      authenticator_class: google
```

Downgrading back to `3.0.0-alpha.1.git.6194.h835c3fa8` regained functionality. I made no changes to the `config.yaml` or the singleuser image, and haven't had any issues on several previous helmcharts. Not sure if this is related to moving from `4.0.0` to `4.0.1`.

#### Expected behaviour

Log in would proceed as usual.

#### Actual behaviour

I receive a 403 error.

### How to reproduce

1. Upgrade to helmchart `3.0.0-beta.3.git.6268.h16086582`.
2. Attempt to login using Google Authenticator

### Your personal set up

 - OS:
 
 - Version(s): Jupyterhub 4.0.1 on Kubernetes (GCP) seems to cause the error, or at least the most recent helmchart that contains 4.0.1
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
