### ISSUE TITLE
tljh-reload stuck in infinite loop of Hub not ready: (HTTP status 502) InsecureRequestWarning: Unverified HTTPS request is being made to host while setting up azuread OAuthenticator

### ISSUE THREAD

**Issue by mhatremahesh** [jupyterhub/jupyterhub#4661]
### Bug description

While setting up OAuthenticator for azuread following this documentation: https://oauthenticator.readthedocs.io/en/latest/tutorials/provider-specific-setup/providers/azuread.html

sudo tljh-config reload is stuck in infinite loop of: Hub not ready: (HTTP status 502)
/opt/tljh/hub/lib/python3.10/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

and
accessing the jupyterhub shows bad gateway exception in the browser. (mostly because relaod isn't finished)

### How to reproduce
1. Create a JupyterHub
2. Enable https for it
3. In JupyterHub config:
```
auth:
    OAuthenticator:
        client_id: <client id created in azure ad using app registration>
        client_secret: <client secret created in azure ad using app registration>
    type: azuread
AzureAdOAuthenticator:
  tenant_id: <tenant id created in azure ad using app registration>
  scope: '[Read]'
```

4. Run: 'sudo tljh-config reload'

#### Expected behaviour

The tljh-config reload should finish and accessing the server should show sign in screen of azure ad

#### Actual behaviour

Exception in browser 'Bad Gateway'

### Your personal set up

Using the-littlest-jupyterhub on azure vm
 - OS:
 
 - Linux (ubuntu 22.04)
 
jupyterhub version 4.0.2
Python 3.10.10

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
