### ISSUE TITLE
Singleuser: empty host is treated as `127.0.0.1` instead of `*`

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#4985]
### Bug description

Set `c.Spawner.ip = ""`. This should cause the singleuser server to listen on _all_ interfaces (IPv4 and IPv6). Instead it listens on `127.0.0.1`.

### How to reproduce

Set `c.Spawner.ip = ""` on a remote spawner, e.g. KubeSpawner.
JupyterHub will spawn the singleuser container but won't be able to connect, because the singleuser server listens on `127.0.0.1`

#### Expected behaviour

Singleuser server should listen on _all_ interfaces (IPv4 and IPv6)

#### Actual behaviour

Singleuser server listens on `127.0.0.1` only.

I think this is due to `url.hostname` being empty when `JUPYTERHUB_SERVICE_URL=http://:8888/user/test/` is parsed, which is treated as `127.0.0.1` in the singleuser code:

https://github.com/jupyterhub/jupyterhub/blob/2550d24048c6b7a51ff03138c28c9bb59d390972/jupyterhub/singleuser/extension.py#L511-L521

https://github.com/jupyterhub/jupyterhub/blob/2550d24048c6b7a51ff03138c28c9bb59d390972/jupyterhub/singleuser/mixins.py#L287-L291

### Your personal set up

```yaml
# helm upgrade --install jh --repo=https://hub.jupyter.org/helm-chart/ jupyterhub --version=4.1.0 -f z2jh-config.yaml --wait

custom:
  netpol: &netpol
    networkPolicy:
      enabled: false

hub:
  config:
    JupyterHub:
      default_url: /hub/home
      cleanup_servers: true
    Spawner:
      http_timeout: 600
    #  start_timeout: 600
    KubeSpawner:
      # ip: "[::]"
      ip: ""
  <<: *netpol

proxy:
  service:
    type: ClusterIP
  chp:
    <<: *netpol

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

singleuser:
  image:
    name: quay.io/jupyter/base-notebook
    tag: latest
  <<: *netpol

ingress:
  enabled: true
  hosts:
    - <HOSTNAME>
```
