### ISSUE TITLE
Is there a way to use Django in an Ipython Notebook? How?

### ISSUE THREAD

**Issue by pylotpro** [jupyterhub/jupyterhub#803]
Hi, my group are trying to learn Python and Django and need use jupyterhub, someone know the way to use Django in the notebooks?
thanks in advance,

**Comment by willingc** [comment]
Hi @pylotpro,

That's great that you and your group are learning Python and Django. As you know, learning Python with the notebooks is helpful.

I'm confused as to why you would wish to run Django in a notebook.

I would highly recommend using the [Django Girls Tutorial](https://djangogirls.org/resources/) and the [Django docs tutorial](https://docs.djangoproject.com/en/1.10/intro/) to learn Django. They've been tested by 1000s and are very well maintained.

**Comment by pylotpro** [comment]
Hi @willingc,
Thanks for your quick response, yes for Django think is better user Django Girls Tutorial && Django docs tutorial.

I searched all afternoon and finally found the tool you need: 
[jupyterhub-deploy-teaching](https://github.com/jupyterhub/jupyterhub-deploy-teaching)

But need step by step installation guide, I have a clean VPS and tried this and don't successes.. 
[jupyterhub+nbgrader](http://kristenthyng.com/blog/2016/09/07/jupyterhub+nbgrader/)

**Would be great if you can tell me how deploy using docker** :+1: 

I'm building from this:
[oauthenticator](https://github.com/jupyterhub/oauthenticator/blob/master/example/Dockerfile)
**docker guild -t demo/jupyterhub-oaut .**

and after use my **docker-compose.yml**

```
jupyterhub-oaut:
  restart: always
  image: demo/jupyterhub-oaut
  container_name: jupyterhub-oaut.dev
  environment:
    - VIRTUAL_HOST=jupyterhub-oaut.dev,www.jupyterhub-oaut.dev
    - GITHUB_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxx
    - GITHUB_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - OAUTH_CALLBACK_URL=https://jupyterhub-oaut.dev/hub/oauth_callback
```
